### ISSUE TITLE
Implement querystring params

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/dagula-gateway#5]
https://github.com/ipfs/specs/blob/main/http-gateways/PATH_GATEWAY.md#request-query-parameters

**Comment by vasco-santos** [comment]
Note that format parameter is already being handled. So, missing `filename` + `download`

**Comment by vasco-santos** [comment]
Needs gateway-lib applied here to close :) github is on a rush to close things

**Comment by alanshaw** [comment]
We're still missing filename + download

**Comment by alanshaw** [comment]
Wait, sorry those were added in https://github.com/web3-storage/gateway-lib/pull/4
